### ISSUE TITLE
controlling colours in trace_explorer and process_map

### ISSUE THREAD

**Issue by ChristelSwift** [bupaverse/bupaR#17]
hi there,
thank you for this amazing package :)  
I was wondering if there is a way of controlling colours in the trace_explorer matrix and the process_map nodes?  
i tried something like:
```
trace_explorer(
coverage = 0.65, 
scale_fill = scale_fill_discrete(c("lavender", "cadetblue1", "slateblue","lightgoldenrod1")
)
```
with no luck.
thank you

**Comment by gertjanssenswillen** [comment]
Hi Christel

For trace explorer
To use custom set of colours, you can use scale_fill_manual (instead of scale_fill_discrete). Be aware that in this case, you have to make sure that the number of colours provided matches the number of colours trace explorer needs.  

For process_map
The colours of the nodes can be changed, but for this, you can only use sequential, continuous scales. The default scale is PuBu. You can use the RColorBrewer package to specify other scales. You can check them with the following statement:

RColorBrewer::brewer.pal.info

Those were category = seq can be used for the nodes of the process_map.
