### ISSUE TITLE
processing_time doesnt work when group by resource_id

### ISSUE THREAD

**Issue by kc3cheng** [bupaverse/bupaR#20]
Hi,
I encountered the following error when trying to use processing_time after grouping by resource

![bug_group_by_resource_id](https://user-images.githubusercontent.com/38797793/86830107-3fa08080-c063-11ea-8c2d-043767fe9ac6.JPG)

However, after setting resource to another variable and then group by resource (the variable previously being assigned as resource_id), it works. 

![bug_group_by_resource_id_2](https://user-images.githubusercontent.com/38797793/86830411-a9b92580-c063-11ea-803b-51c989936b43.JPG)

Can anyone figure out the error? Thanks! 

NOTE: the dataset sepsis used is available in bupaR package.

**Comment by gertjanssenswillen** [comment]
At this moment it is advised not to use group_by with any mapped process component (or the short cuts) when computing metrics. 

Instead, you can use the "resource-activity" level in processing_time, to compute processing times for combinaties of resources and acitivites

OR

you can create a duplicate column of the resource id and use this to do the grouping. 

Several edeaR functionalities currently do not work when the log is grouped on a one of the components. This issue is to be resolved in future version those. The levels in metrics (such as processing time) also have the role of a "grouping" which is used preferably. 

Hope this helps. It is a known issue and a generic solution is still to be created.

(The group_by shortcuts such as group_by_resource are created to help with event data manipulation steps, where they can still be helpful).

**Comment by kc3cheng** [comment]
Thanks for the response!
